/* eslint no-multi-spaces: 0 */

export const FETCH_ALL            = 'FETCH_ALL';
export const FETCH_ONE            = 'FETCH_ONE';
export const HIDE_MODAL           = 'HIDE_MODAL';
export const SET_QUERY_PARAMS     = 'SET_QUERY_PARAMS';
export const SCROLL               = 'SCROLL';
export const SET_CATEGORIES       = 'SET_CATEGORIES';
export const SET_CONFIG           = 'SET_CONFIG';
export const SET_CURRENCIES       = 'SET_CURRENCIES';
export const SET_CURRENT_CURRENCY = 'SET_CURRENT_CURRENCY';
export const SET_CURRENT_DISCOUNT = 'SET_CURRENT_DISCOUNT';
export const SET_DISCOUNTS        = 'SET_DISCOUNTS';
export const SET_FILTER_PARAMS    = 'SET_FILTER_PARAMS';
export const SET_FILTER_VALUES    = 'SET_FILTER_VALUES';
export const SET_ORDER            = 'SET_ORDER';
export const SET_ORDERS           = 'SET_ORDERS';
export const SET_PER_PAGE         = 'SET_PER_PAGE';
export const SET_PRODUCT          = 'SET_PRODUCT';
export const SET_SEARCH           = 'SET_SEARCH';
export const SET_SIZE_DATA        = 'SET_SIZE_DATA';
export const SET_TOKEN            = 'SET_TOKEN';
export const SET_USER             = 'SET_USER';
export const SHOW_MODAL           = 'SHOW_MODAL';
export const UNSET_TOKEN          = 'UNSET_TOKEN';
export const UNSET_USER           = 'UNSET_USER';
